---
- name: Converge
  hosts: all
  pre_tasks:
    - name: Create backup user for testing
      ansible.builtin.user:
        name: backup
        group: backup
        create_home: true
  roles:
    - role: boutetnico.restic
      restic_password_files:
        - path: /etc/restic/repo-password
          password: secret
        - path: /home/backup/.restic/backup-password
          password: backup-secret
          owner: backup
          group: backup
